Embeds:
  GiveawayCreated:
    title: "ğŸ Giveaway"
    description: "{description}"
    color: "{color-default}"
    fields:
      - name: "Prize"
        value: "{prize}"
        inline: true
      - name: "â €"
        value: "â €"
        inline: true
      - name: "Winners"
        value: "{winners}"
        inline: true
      - name: "Hosted By"
        value: "<@{hostedBy}>"
        inline: true
      - name: "â €"
        value: "â €"
        inline: true
      - name: "Giveaway Ends"
        value: "<t:{timestamp}:R>"
        inline: true
      - name: "â €"
        value: "**Use the button below to participate in the giveaway!**"
  GiveawayEnded:
    title: "ğŸ Giveaway Ended"
    description: "{description}"
    color: "{color-default}"
    fields:
      - name: "Prize"
        value: "{prize}"
        inline: true
      - name: "â €"
        value: "â €"
        inline: true
      - name: "Winners"
        value: "{winners}"
        inline: true
      - name: "Hosted By"
        value: "<@{hostedBy}>"
        inline: true
      - name: "â €"
        value: "â €"
        inline: true
      - name: "Giveaway Ends"
        value: "Ended."
        inline: true
      - name: "â €"
        value: "**Thank you for participating in the giveaway**"
  GiveawayEntryRegistered:
    title: "ğŸ Your entry to this giveaway has been successfully registered"
    color: "Green"
  UserMessagesEmbed:
    title: "{user-username}"
    description: "You sent a total of **{messages}** messages in this server."
    color: "{color-default}"
    footer:
      text: "{bot-username}"
      iconURL: "{bot-avatar}"
  CreateTicketEmbed:
    title: "Support Tickets"
    color: "{color-default}"
    description: |
      ğŸŒŸ Hello there! Having trouble? Looking for help?
      Support tickets are the best way to get in contact with our staff teams.

      **Ticket Categories:**
      {categories}

      â° Staff try to reply as fast as possible in each ticket, so please don't ping staff unless its urgent.
    footer:
      text: "{bot-username} â€¢ Support System"
      iconURL: "{bot-avatar}"
  UserAlreadyHaveTicketEmbed:
    title: "You have exceeded the maximum number of tickets allowed"
    color: "{color-default}"
  CreatedTicketEmbed:
    title: "Support System"
    description: "Your ticket has been created <#{channel-id}>"
    color: "{color-default}"
  TicketMainEmbed:
    title: "{emoji} {name}"
    color: "{color-default}"
    description: |
      Thank you for reaching out for support! Staff will be with you shortly.
      In the meantime, please answer the following question(s)"
    fields:
      - name: "ğŸ· Ticket Category"
        value: "{name}"
        inline: true
      - name: "ğŸ‘¤ Ticket Owner"
        value: "<@{user-id}>"
        inline: true
      - name: "â° Created At"
        value: "<t:{timestamp}:R>"
        inline: true
    footer:
      text: "{bot-username} â€¢ Support System"
      iconURL: "{bot-avatar}"
  TicketManageEmbed:
    title: "This ticket has been closed by {user-username}"
    color: "{color-default}"
  OpenedTicketEmbed:
    title: "This ticket has been opened by {user-username}"
    color: "{color-default}"
  ClaimedTicketEmbed:
    title: "This ticket has been claimed by {user-username}"
    color: "{color-default}"
  DeleteTicketEmbed:
    title: "This ticket will be deleted in 5 seconds (action by {user-username})"
    color: "{color-default}"
  TranscriptEmbed:
    color: "{color-default}"
    author:
      name: "{owner-username} ({owner-id})"
      iconURL: "{owner-avatar}"
    fields:
      - name: "Ticket Owner"
        value: "<@!{owner-id}>"
        inline: true
      - name: "Ticket Name"
        value: "{ticket-name}"
        inline: true
      - name: "Category Name"
        value: "{category-name}"
        inline: true
      - name: "Direct Transcript"
        value: "[Direct Link]({transcript-url})"
        inline: true
      - name: "Ticket Closed"
        value: "{staff-tag}"
        inline: true
  TranscriptCreatedEmbed:
    title: "The transcript has been send successfully"
    color: "{color-default}"
  UserJoinedEmbed:
    title: "ğŸ‘‹ Welcome to {guild-name}"
    color: "{color-default}"
    description: |
      <@!{user-id}>. thank you for joining this great community,
      you are our member **{memberCount}**, your account was created <t:{createdTimestamp}:R>

      **Â» User Information**
      â€¢ Username: **{user-username}**
      â€¢ Joined At: <t:{joinedTimestamp}:R>
    thumbnail:
      url: "{user-avatar}"

Buttons:
  GiveawayActiveButton:
    Label: "Participate"
    Style: "Primary"
    Emoji: "ğŸ‰"
  GiveawayEndedButton:
    Label: "Ended"
    Style: "Secondary"
    Emoji: "ğŸ‰"
  CloseTicketButton:
    Label: "Close"
    Style: "Secondary"
    Emoji: "ğŸ”’"
  ClaimTicketButton:
    Label: "Claim"
    Style: "Secondary"
    Emoji: "ğŸ‘‹"
  OpenTicketButton:
    Label: "Open"
    Style: "Secondary"
    Emoji: "ğŸ”“"
  DeleteTicketButton:
    Label: "Delete"
    Style: "Secondary"
    Emoji: "ğŸ—‘"
  TranscriptTicketButton:
    Label: "Transcript"
    Style: "Secondary"
    Emoji: "ğŸ“‘"

Strings:
  DefaultColor: "Aqua"
  GiveawayWinnerMessage: "Congratulations, {winners}, you won **{prize}**!"
  TicketCategoryParsed: "{emoji} Â» {name}"
