Embeds:
  GiveawayCreated:
    title: "ğŸ Giveaway"
    description: "{description}"
    color: "{color-default}"
    fields:
      - name: "Prize"
        value: "{prize}"
        inline: true
      - name: "â €"
        value: "â €"
        inline: true
      - name: "Winners"
        value: "{winners}"
        inline: true
      - name: "Hosted By"
        value: "<@{hostedBy}>"
        inline: true
      - name: "â €"
        value: "â €"
        inline: true
      - name: "Giveaway Ends"
        value: "<t:{timestamp}:R>"
        inline: true
      - name: "â €"
        value: "**Use the button below to participate in the giveaway!**"
  GiveawayEnded:
    title: "ğŸ Giveaway Ended"
    description: "{description}"
    color: "{color-default}"
    fields:
      - name: "Prize"
        value: "{prize}"
        inline: true
      - name: "â €"
        value: "â €"
        inline: true
      - name: "Winners"
        value: "{winners}"
        inline: true
      - name: "Hosted By"
        value: "<@{hostedBy}>"
        inline: true
      - name: "â €"
        value: "â €"
        inline: true
      - name: "Giveaway Ends"
        value: "Ended."
        inline: true
      - name: "â €"
        value: "**Thank you for participating in the giveaway**"
  GiveawayEntryRegistered:
    title: "ğŸ Your entry to this giveaway has been successfully registered"
    color: "Green"
  UserMessagesEmbed:
    title: "{user-username}"
    description: "You sent a total of **{messages}** messages in this server."
    color: "{color-default}"
    footer:
      text: "{bot-username}"
      iconURL: "{bot-avatar}"

Buttons:
  GiveawayActiveButton:
    Label: "Participate"
    Style: "Primary"
    Emoji: "ğŸ‰"
  GiveawayEndedButton:
    Label: "Ended"
    Style: "Secondary"
    Emoji: "ğŸ‰"

Strings:
  DefaultColor: "Aqua"
  GiveawayWinnerMessage: "Congratulations, {winners}, you won **{prize}**!"
